### ISSUE TITLE
Error: TrustFailure (The authentication or decryption has failed.)

### ISSUE THREAD

**Issue by rfay** [Linuturk/mono-choco#17]
Possibly related to #8 

In the last month I've been unable to use mono-choco at all because a push results in a TrustFailure:

```
docker run --rm -v $PWD:/tmp/chocolatey -w /tmp/chocolatey linuturk/mono-choco push -s https://push.chocolatey.org/ --api-key=<key>
Chocolatey v0.10.15.0
Directory 'opt/chocolatey/lib' does not exist.

Chocolatey is not an official build (bypassed with --allow-unofficial).
 If you are seeing this message and it is not expected, your system may
 now be in a bad state. Only official builds are to be trusted.

Attempting to push ddev.1.11.1.nupkg to https://push.chocolatey.org/
Error: TrustFailure (The authentication or decryption has failed.)
```

I'm able to push the exact same package on Windows using `choco push`

**Comment by rekire** [comment]
It seems that this is [a bug in mono 3.0](https://xamarin.github.io/bugzilla-archives/26/26658/bug.html), but since this release is totally outdated the mono project just dropped the support. There is a quite old [PR for chocolaty](https://github.com/chocolatey/choco/pull/1827) to use a newer version of the .net framework which aims to fix this bug. Let up hope that this will be merged soon, so that @Linuturk can create a new image.

**Comment by Linuturk** [comment]
I subscribed to the linked PR. I'll keep an eye out.

**Comment by TheCakeIsNaOH** [comment]
I think it is caused by- https://github.com/chocolatey/chocolatey.org/issues/584

**Comment by rekire** [comment]
You could publish a "patched" version with this workaround: https://github.com/chocolatey/chocolatey.org/issues/584#issuecomment-538702620 this is a bit hacky, but not causing security issues out of my view.

**Comment by rfay** [comment]
This was resolved by https://github.com/chocolatey/chocolatey.org/issues/584
